// DOM element references
export const checkboxes = document.querySelectorAll('.day-checkboxes input[type="checkbox"]');
export const startTimeInput = document.getElementById('start-time');
export const endTimeInput = document.getElementById('end-time');
export const submitButton = document.getElementById('submit-btn');
export const editScheduleButton = document.getElementById('edit-schedule-btn');
export const editScheduleButtonBottom = document.getElementById('edit-schedule-btn-bottom');
export const settingsPanel = document.getElementById('settings-panel');
export const progressBar = document.getElementById('progress-bar');
export const progressText = document.getElementById('progress-text');
export const hoursWorkedEl = document.getElementById('hours-worked');
export const totalHoursEl = document.getElementById('total-hours');
export const percentageEl = document.getElementById('percentage');
export const statusMessage = document.getElementById('status-message');
export const statusText = document.getElementById('status-text');
export const shiftProgressSection = document.getElementById('shift-progress-section');
export const shiftLabel = document.getElementById('shift-label');
export const shiftProgressBar = document.getElementById('shift-progress-bar');
export const shiftProgressText = document.getElementById('shift-progress-text');
export const shiftTimeInfo = document.getElementById('shift-time-info');
export const toggleShiftButton = document.getElementById('toggle-shift-view');
